version: "3"

services:
  caddy:
    build:
      context: "./docker/proxy"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/proxy/config/Caddyfile:/etc/caddy/Caddyfile
      - ./app:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
